# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: macos-11

steps:
- task: DownloadSecureFile@1
  name: DeveloperCertificate
  displayName: 'Download Developer Certificate'
  inputs:
    secureFile: '${{cfi}}_development.p12'
- task: InstallAppleCertificate@2
  inputs:
    certSecureFile: '${{cfi}}_development.p12'
    certPwd: '$(cert_passwd)'
    keychain: 'temp'
  displayName: 'Install Developer Certificate'
  
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
